name: Request
description: Submit a request regarding the use of afetcan.
title: "[Request]: "
labels: ["request"]
body:
  - type: markdown
    attributes:
      value: |
        Have a nice day, opening a well-written issue makes it easier for our team. Please open an issue by following the steps below.

  - type: input
    id: summary
    attributes:
      label: Short summary
      description: Please enter a brief summary of your issue.
      placeholder: ex. "help id needs to return data when I make a request."
    validations:
      required: false

  - type: textarea
    id: istek
    attributes:
      label: Description of your request
      description:  Please explain what your issue is. Be overly descriptive.
      placeholder: ex. "When I send a help id, it will return the help information. It will not be an Array, only a single help information will be returned."
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What was the result of your request supposed to be?
      description: "Please explain what your issue should be."
      placeholder: ex. "Let's get back to just one piece of help information."
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Please choose which platform your issue is on.
      options:
        - Website (Default)
        - i18n
        - API
        - Components
        - UX
        - UI
        - Other
    validations:
      required: true
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      multiple: true
      options:
        - Low
        - Medium
        - High
  - type: checkboxes
    id: check
    attributes:
      label: Did you follow the steps above?
      description:  Please make sure your issue is following the steps above.
      options:
        - label: "Yes, I am sure."
          required: true
          